### ISSUE TITLE
Index existing database?

### ISSUE THREAD

**Issue by cliquenoir** [bkabrda/flask-whooshee#10]
Good day,

Happy to be putting whooshee through its paces. Quick question: is there a way to re/index data that existed prior to integrating whooshee?

Thanks in advance for any guidance.

**Comment by bkabrda** [comment]
Hi, there is a PR https://github.com/bkabrda/flask-whooshee/pull/5 from @xsuchy, which implements this. It looks good, but I wanted the submitter to implement a real test, which he didn't, yet... When that is done, I'll accept the PR and release new version.
@xsuchy, still interested in working on that PR?

**Comment by xsuchy** [comment]
Wow, I totally forgot about that. I will try to find some time to finish it. However if @cliquenoir enhance it and submit as new PR I would be happy.

**Comment by bkabrda** [comment]
This issue was fixed by #5, so I'm closing it. I'll release new version shortly.

**Comment by bkabrda** [comment]
Here's the new release: https://pypi.python.org/pypi/flask-whooshee/0.0.9
Enjoy!

**Comment by cliquenoir** [comment]
Thanks guys! Look forward to testing this out. Cheers.
