### ISSUE TITLE
Supporting sqlalchemy's aliased()

### ISSUE THREAD

**Issue by kaihil** [bkabrda/flask-whooshee#11]
At the moment it doesn't seem to be possible to do a whooshee_search on a query that uses the sqlalchemy command `aliased()`. It fails while comparing the Whoosheer's model list with the entity list generated by flask-whooshee from the query, even if i put a `aliased(ExampleModel)` into the Whoosheer's model list.
It would be great to be able to use `aliased()`, because it allows to use a Model that has multiple relationships with another specific Model in a comfortable manner.

**Comment by bkabrda** [comment]
Interesting. I'll try looking into this and see what I can do about that. Thanks for the report!

**Comment by bkabrda** [comment]
So I think I managed to handle this, the fix will be part of next release.

**Comment by bkabrda** [comment]
Released in https://pypi.python.org/pypi/flask-whooshee/0.4.1 - enjoy!
