### ISSUE TITLE
possibility to register model before calling init_app?

### ISSUE THREAD

**Issue by cod3licious** [bkabrda/flask-whooshee#21]
In my Flask setup I have a `__init__.py` file sort of like this:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_whooshee import Whooshee
from config import config

db = SQLAlchemy()
whooshee = Whooshee()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    whooshee.init_app(app)
    return app
```

and in `models.py` i import whooshee and register my model:

```
from . import db, whooshee
@whooshee.register_model('text')
class Article(db.Model):
    text = db.Column(db.UnicodeText)
```

but then i get an error:
`.../python2.7/site-packages/flask_whooshee.py", line 173, in register_whoosheer
    wh.search_string_min_len = self.search_string_min_len
AttributeError: 'Whooshee' object has no attribute 'search_string_min_len'`
because the init_app function wasn't called yet and `search_string_min_len` is not set to anything.

is there a better way to set up my code in this case (i followed the guidelines from here http://flaskbook.com/)? is it a bug, e.g. could this be fixed by setting all class variables in `Whooshee.__init__` to `None`? or is there a way to register my models at a later point, e.g. after i have called `whooshee.init_app(app)`?

Thanks!!

**Comment by bkabrda** [comment]
Hi, thanks for reporting this. I know that quite a lot of flask extension do have a way to do this, e.g. flask-sqlalchemy has the option to do:
```
db = SQLAlchemy()
# ... create app object
db.init_app(app)
```

So yeah, it definitely makes sense to have this, I'm just not sure when I'll get the time to implement it. I'll try ASAP. PR's are welcome, if you need this soon and feel like implementing that!

**Comment by cod3licious** [comment]
cool! yeah, i have no experience in programming flask extensions but your code seems reasonably short so i'll give it a try! :)

**Comment by bkabrda** [comment]
Cool! Feel free to open a work-in-progress PR and I can share some pointers/comments if you're stuck.

**Comment by sh4nks** [comment]
I am not using the decorator to register the model/whooshee and it works just fine:
```python
from flaskbb.extensions import whooshee
from flaskbb.utils.search import PostWhoosheer

    
def create_app(config=None):
    # ... your flask stuff
    whooshee.init_app(app)
    whooshee.register_whoosheer(PostWhoosheer)
```
Check out this (https://github.com/sh4nks/flaskbb/commit/3559c3da26b917fc385e580763deacbded3042a1) commit for a better example :)

PS: I am not sure if Flask-Whooshee is supposed to be used like this.

**Comment by cod3licious** [comment]
ah, i see, but you're using the whoosh schema while i was trying to stick with my existing sqlalchemy models. i wouldn't mind registering the models later after calling init_app tough, i.e. without the decorator. is this possible while sticking to sqlalchemy models?

**Comment by bkabrda** [comment]
I have to admit I'm actually confused now :)
I have a lot on my plate ATM and can't really investigate, so I'll leave this discussion up to you guys for the moment and get back to it when I can. Thanks to both of you!

**Comment by sh4nks** [comment]
Thats okay ;)
I think what he meant is, that he doesn't want to write the whooshers by himself but simply wants the extension to handle it for him (which is ok, if he doesn't the advanced stuff).

This should work for you:
```python
whooshee.register_model('title', 'content')(YourSQLAlchemyModel)
```

It's not the nicest way to do in my opinion and can be for sure improved :)

**Comment by cod3licious** [comment]
yes, this is what i had thought as well, just don't know if this messes anything up later since those values are used somewhere, e.g. in `register_whoosheer` it sets `wh.search_string_min_len = self.search_string_min_len` and if the decorator is called before init_app then i suppose those values would be set wrongly if i set them to different values later when initialising?

**Comment by cod3licious** [comment]
i have also tried calling the register_model later as you've suggested however this doesn't seem to work, i might have a bug somewhere else but for now when i call `whooshee_search(q)` i just get `null` in the query....

**Comment by bkabrda** [comment]
Hey, so I implemented support for your use-case. I'm somewhat confident that I didn't break anything, but if you can, please test! I'll try to do new release in several days.

**Comment by sh4nks** [comment]
I have added a comment to your commit :) Nice to see some activity here. Would you be interested if I create some docs with sphinx?

**Comment by bkabrda** [comment]
Thanks @sh4nks. Your comment made me realize that I have the implementation kind of backwards (mostly the work in the commits following this one). I took a look at some of the approved extensions and I see that I'll have to redo the way that Whooshee class works with potential multiple apps... I'll do the changes and we'll see if it's going to make sense :)

**Comment by bkabrda** [comment]
BTW having some sphinx docs created would be lovely. I was already thinking about registering this project at readthedocs and do automatic docs builds there, so creating sphinx docs is a great first step.
