### ISSUE TITLE
Flask-SQLAlchemy tracking commits

### ISSUE THREAD

**Issue by jtl999** [bkabrda/flask-whooshee#25]
Hi

Integrating Flask-Whooshee with my application. 

Quick question. I noticed that added data to my schema wasn't being automatically added to the index and I noticed that Flask-Whoshee uses `models_committed` which requires `SQLALCHEMY_TRACK_MODIFICATIONS` which has been called "buggy" in the past in my case with `SQLALCHEMY_TRACK_MODIFICATIONS` enabled I run into `This session is in 'committed' state; no further SQL can be emitted within this transaction` due to SQL being ran on each page load. Is it possible that Flask-Whooshee could use SQLAlchemy event system or similar to avoid this problem? Thanks.

**Comment by bkabrda** [comment]
Hi, thanks for the report. I don't have a quick answer right now, I'll try to have a look over the weekend. I'll need to see and understand the events system first.

**Comment by jtl999** [comment]
Thanks

**Comment by jtl999** [comment]
This looks useful.

http://docs.sqlalchemy.org/en/latest/orm/events.html#sqlalchemy.orm.events.SessionEvents.after_commit

Now how to get the changed models from the session object?

**Comment by jtl999** [comment]
I rewrote part of Flask-Whooshee tonight to use the event system of SQLAlchemy.

In my initial testing it works 100%, but shouldn't be taken as exhaustive.

Should I send in a pull request now?

**Comment by bkabrda** [comment]
That sounds awesome. Sending a PR would help a lot, because other stuff in my personal life is taking all of my time and I don't really know when I'd get to this.

**Comment by bkabrda** [comment]
Closed by https://github.com/bkabrda/flask-whooshee/pull/26

**Comment by bkabrda** [comment]
Released in 0.3.0: https://pypi.python.org/pypi/flask-whooshee/0.3.0
