### ISSUE TITLE
Build/Run requirements

### ISSUE THREAD

**Issue by MrMEEE** [bkabrda/flask-whooshee#32]
Hi..

In the Fedora RPM build, the packages: python3-flask-sqlalchemy, python3-blinker and python3-flask are requirements for both building and running...

I seem to have no problems with building and running without these packages... are they needed for something????

Regards??

**Comment by bkabrda** [comment]
Hi, how did you install flask-whooshee? By pip? If so, it downloaded these packages from PyPI as well, so you wouldn't need RPMs in that case.

**Comment by bkabrda** [comment]
No response and I couldn't find any issue with build/run requirements, therefore I'm closing this issue. Feel free to reopen with further info if you have more problems.
