### ISSUE TITLE
enable/disable whooshee indexing from config

### ISSUE THREAD

**Issue by sepro** [bkabrda/flask-whooshee#33]
During development I would like the option to disable the indexing (importing a large test-set takes considerably longer with Whooshee indexing the descriptions).

Perhaps a flag WHOOSHEE_ENABLE_INDEXING could be implemented to allow disabling through the config file this when not required.

**Comment by bkabrda** [comment]
👍 makes total sense to me. This should be pretty straightforward, I'll look into it.

**Comment by bkabrda** [comment]
Done. Would it be possible for you to verify that this works ok before I do a new release?

**Comment by sepro** [comment]
Cool, will have a look tomorrow to check if it works.

**Comment by sepro** [comment]
Did a quick test (uploaded a data-set twice, once the flag set to True and False, monitoring the run time) and it seems to work.  
Thank you for adding this, very useful for testing one of my projects!

**Comment by bkabrda** [comment]
Thanks for testing! Unfortunately Travis CI seems unhappy with the changes, but that probably just means that I created the tests in a wrong way. I'll fix it and release a new version soon (perhaps today, if time permits).

**Comment by bkabrda** [comment]
Yeah, of course it was a (stupid) bug in the tests 🤦‍♂️ https://github.com/bkabrda/flask-whooshee/commit/3b9380bc04a778ef99a1cf9082c0c64184bb9447

**Comment by bkabrda** [comment]
Released as part of flask-whooshee 0.5.0: https://pypi.python.org/pypi/flask-whooshee/0.5.0
