### ISSUE TITLE
Flask-Whooshee overwrites custom query class.

### ISSUE THREAD

**Issue by justanr** [bkabrda/flask-whooshee#41]
In FlaskBB we're attempting to implement a [soft-delete feature](https://github.com/sh4nks/flaskbb/issues/36) by way of the linked blog post. However, we also index several of these models with Whooshee, which loses the custom query class.

[Offending line](https://github.com/bkabrda/flask-whooshee/blob/8bda1dd7b4351c9ebfca5849c624979b446d226a/flask_whooshee.py#L269)

Looks like a simple fix could be to check if there is a query class already registered to the model and augment it with the whooshee query class, something like the following might work.

```python
query_class = getattr(model, 'query_class', None)
# check type to ensure stable MRO
if model.query_class is not None and query_class is not BaseQuery:
    query_class_name = model.query_class.__name__
    model.query_class = type('Whooshee{}'.format(query_class_name), (model.query_class, WhoosheeQuery), {})
else:
    model.query_class = WhoosheeQuery
```

I'm going to test this in FlaskBB and see how it works and issue a PR if there is interest in this.

**Comment by bkabrda** [comment]
Fixed by #42, closing.
