### ISSUE TITLE
Exceptions in whoosheer doesnt unlock lock file

### ISSUE THREAD

**Issue by thejcannon** [bkabrda/flask-whooshee#48]
In an `insert_foo`/`update_foo`/`delete_foo` method, if the code throws, the writer isn't cancelled and the lock file isn't unlocked.

**Comment by bkabrda** [comment]
Yup, definitely a bug. Will fix it, thanks for the report.

**Comment by bkabrda** [comment]
Released in https://pypi.org/project/flask-whooshee/0.7.0/
